const express = require('express')
const cors = require('cors')
const app = express()
app.use(cors())

const port = 8000


msg = {
    "opt": [
        "London",
        "Birmingham",
        "Manchester",
        "Liverpool",
        "Leeds",
        "Sheffield",
        "Bristol",
        "Newcastle upon Tyne",
        "Sunderland",
        "Wolverhampton", //
        "Plymouth",
        "Nottingham",
        "Leicester",
        "Stoke-on-Trent",
        "Southampton",
        "Reading",
        "Derby",
        "Dudley",
        "Coventry",
        "Northampton",
        "Portsmouth",
        "Luton",
        "Preston",
        "Milton Keynes",
        "Aberdeen",
        "Norwich",
        "Walsall",
        "Swansea",
        "Bournemouth",
        "Southend-on-Sea",
        "Swindon",
        "Oxford",
        "Dundee",
        "Huddersfield",
        "Poole",
        "Middlesbrough",
        "Bolton",
        "Blackburn",
        "Peterborough",
        "Stockport",
        "Brighton",
        "Slough",
        "Gloucester",
        "Watford",
        "Rotherham",
        "Newport",
        "Cambridge",
        "Exeter",
        "Eastbourne",
        "Colchester",
        "Crawley",
        "Sutton Coldfield",
        "Blackpool",
        "Birkenhead",
        "Woking",
        "Cheltenham",
        "Chelmsford",
        "Bath",
        "Maidstone",
        "Sale",
        "Carlisle",
        "Doncaster",
        "Wakefield",
        "Hastings",
        "Rochdale",
        "Solihull",
        "Basildon",
        "Worthing",
        "High Wycombe",
        "Basingstoke",
        "Burnley",
        "Worcester",
        "Grimsby",
        "Saint Helens",
        "Weston-super-Mare",
        "Guildford",
        "Southport",
        "Wokingham",
        "Hemel Hempstead",
        "Aylesbury",
        "Lincoln",
        "Barnsley",
        "Stevenage",
        "Harlow",
        "Chesterfield",
        "Oldham",
        "Basingstoke",
        "Chatham",
        "Rugby",
        "Scunthorpe",
        "Gateshead",
        "Eastleigh",
        "Bedford",
        "Hartlepool",
        "Warrington",
        "Shrewsbury",
        "Keighley",
        "Kingston upon Hull",
        "Telford",
        "Bromley"
    ]
}

msg2 = {
    "opt": [
        "CityA1",
        "CityA2",
        "CityA3",
        "CityA4",
        "CityA5",
        "CityA6",
        "CityA7",
        "CityA8",
        "CityA9",
        "CityA10",
        "CityA11",
        "CityA12",
        "CityA13",
        "CityA14",
        "CityA15",
        "CityA16",
        "CityA17",
        "CityA18",
        "CityA19",
        "CityA20",
        "TownB1",
        "TownB2",
        "TownB3",
        "TownB4",
        "TownB5",
        "TownB6",
        "TownB7",
        "TownB8",
        "TownB9",
        "TownB10",
        "TownB11",
        "TownB12",
        "TownB13",
        "TownB14",
        "TownB15",
        "TownB16",
        "TownB17",
        "TownB18",
        "TownB19",
        "TownB20",
        "PlaceC1",
        "PlaceC2",
        "PlaceC3",
        "PlaceC4",
        "PlaceC5",
        "PlaceC6",
        "PlaceC7",
        "PlaceC8",
        "PlaceC9",
        "PlaceC10",
        "PlaceC11",
        "PlaceC12",
        "PlaceC13",
        "PlaceC14",
        "PlaceC15",
        "PlaceC16",
        "PlaceC17",
        "PlaceC18",
        "PlaceC19",
        "PlaceC20",
        "VilleD1",
        "VilleD2",
        "VilleD3",
        "VilleD4",
        "VilleD5",
        "VilleD6",
        "VilleD7",
        "VilleD8",
        "VilleD9",
        "VilleD10",
        "VilleD11",
        "VilleD12",
        "VilleD13",
        "VilleD14",
        "VilleD15",
        "VilleD16",
        "VilleD17",
        "VilleD18",
        "VilleD19",
        "VilleD20",
        "BurgE1",
        "BurgE2",
        "BurgE3",
        "BurgE4",
        "BurgE5",
        "BurgE6",
        "BurgE7",
        "BurgE8",
        "BurgE9",
        "BurgE10",
        "BurgE11",
        "BurgE12",
        "BurgE13",
        "BurgE14",
        "BurgE15",
        "BurgE16",
        "BurgE17",
        "BurgE18",
        "BurgE19",
        "BurgE20",
        "LandF1",
        "LandF2",
        "LandF3",
        "LandF4",
        "LandF5",
        "LandF6",
        "LandF7",
        "LandF8",
        "LandF9",
        "LandF10",
        "LandF11",
        "LandF12",
        "LandF13",
        "LandF14",
        "LandF15",
        "LandF16",
        "LandF17",
        "LandF18",
        "LandF19",
        "LandF20",
        "HamletG1",
        "HamletG2",
        "HamletG3",
        "HamletG4",
        "HamletG5",
        "HamletG6",
        "HamletG7",
        "HamletG8",
        "HamletG9",
        "HamletG10",
        "HamletG11",
        "HamletG12",
        "HamletG13",
        "HamletG14",
        "HamletG15",
        "HamletG16",
        "HamletG17",
        "HamletG18",
        "HamletG19",
        "HamletG20",
        "HamletG220",
        "HamletG2220",
        "MetroH1",
        "MetroH2",
        "MetroH3",
        "MetroH4",
        "MetroH5",
        "MetroH6",
        "MetroH7",
        "MetroH8",
        "MetroH9",
        "MetroH10",
        "MetroH11",
        "MetroH12",
        "MetroH13",
        "MetroH14",
        "MetroH15",
        "MetroH16",
        "MetroH17",
        "MetroH18",
        "MetroH19",
        "MetroH20",
        "UrbanI1",
        "UrbanI2",
        "UrbanI3",
        "UrbanI4",
        "UrbanI5",
        "UrbanI6",
        "UrbanI7",
        "UrbanI8",
        "UrbanI9",
        "UrbanI10",
        "UrbanI11",
        "UrbanI12",
        "UrbanI13",
        "UrbanI14",
        "UrbanI15",
        "UrbanI16",
        "UrbanI17",
        "UrbanI18",
        "UrbanI19",
        "UrbanI20"
    ]
}


app.get('/', (req, res) => {
    res.send('Hello World!')
})

app.get('/options', (req, res) => {
    const start = req.query["start"]
    const end = req.query["end"]
    const filter = req.query["filter"]

    if (filter != "")
        data = msg2["opt"].filter(value => value.toLowerCase().includes(filter.toLowerCase())).slice(start, end)
    else
        data = msg2["opt"].slice(start, end)

    res.status(200).json({ "opt": data })
})


app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})